import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const mulish = Mulish({ subsets: ['latin'], variable: '--font-mul' })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} font-mul flex flex-col min-h-[100dvh] w-full items-center`}>{children}</body>
    </html>
  );
}
